services:
  aest_backend:
    build:
      context: ../backend
      target: backend-local
      args:
        DOCKER_UID: ${DOCKER_UID-1000}
        DOCKER_GID: ${DOCKER_GID-1000}
    volumes:
      - ../backend:/var/www/html/:delegated
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  aest_backend_webserver:
    build:
      context: ../backend
      target: webserver-local
    labels:
      - traefik.http.routers.aest_backend_webserver.rule=Host(`${DOMAIN}`)
    volumes:
      - ../backend:/var/www/html/:delegated
