services:
  aest_backend:
    image: ${REGISTRY_ADDRESS}aest-backend:main
    restart: always
    environment:
      TEMPLATE_PHP_INI: production
      SESSION_SECURE_COOKIE: 1
    volumes:
      - aest_backend_storage:/var/www/html/var/storage

  aest_backend_webserver:
    image: ${REGISTRY_ADDRESS}aest-backend_webserver:main
    restart: always
    volumes:
      - aest_backend_webserver_logs:/static-logs
    labels:
      - traefik.http.routers.aest_backend_webserver.rule=Host(`aest.${DOMAIN}`)
      - traefik.http.routers.aest_backend_webserver.entrypoints=websecure
      - traefik.http.routers.aest_backend_webserver.tls.certresolver=httpsresolver

volumes:
  aest_backend_storage:
  aest_backend_webserver_logs:
